 knowledge_id |                                                                                                                    content                                                                                                                     | domain_id |  source_type   | initial_character_id | initial_strength | complexity_score |                 concept                  
--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------+----------------------+------------------+------------------+------------------------------------------
 #600001      | Tanuki are supernatural shape-shifting raccoon dogs in Japanese mythology                                                                                                                                                                      | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What are Tanuki in Japanese mythology?
 #600002      | Shapeshifting is the Tanuki's primary supernatural power, an art in which they are considered unparalleled among yōkai. The saying goes "The fox has seven disguises, the Tanuki has eight."                                                   | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is shapeshifting in Tanuki mytholog
 #600003      | Tanuki-bayashi is mysterious festival music that seems to emanate from deep within the woods at night, described as "pom poko" or "ponpon," created by Tanuki drumming on their bellies or scrotums.                                           | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is Tanuki-bayashi?
 #600004      | The kintama is the Tanuki's enormous magical scrotum, meaning both "testicles" and "golden balls." It's used as a versatile tool - weapon, fishing net, boat, umbrella, or blanket - and symbolizes financial luck.                            | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is the kintama?
 #600005      | The three most famous Tanuki are Danzaburou-danuki of Sado Island, Shibaemon-Tanuki of Awaji Island, and Yashima no Hage-Tanuki of Shikoku - each supreme commanders with legendary transformation skills.                                     | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | Who are the three legendary Tanuki?
 #600006      | Tanuki and kitsune are Japan's shapeshifting rivals. While kitsune transform for serious purposes like revenge, Tanuki do so for fun, food, and pranks. Tanuki are superior tricksters but more jovial and bumbling.                           | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | How do Tanuki compare to kitsune?
 #600007      | A tale where a grateful Tanuki transforms into a tea kettle to repay a kind man's rescue. When heated, the kettle screams and runs away, then helps the man get rich by performing acrobatic shows.                                            | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is Bunbuku Chagama?
 #600008      | Ceramic Tanuki statues representing the "Eight Aspects of Good Fortune" - straw hat (protection), big eyes (perception), sake bottle (virtue), big tail (strength), friendly smile (good business).                                            | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What are Shigaraki statues?
 #600009      | Tanuki often place a leaf on their head to initiate shapeshifting. They can become animals, humans, or inanimate objects like stones and teapots, though their disguises may have flaws.                                                       | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | How do Tanuki initiate transformations?
 #600010      | The great Tanuki war between Kinchō-Tanuki and Rokuemon-Tanuki, with armies of over 600 Tanuki battling for three days and nights across the Katsuura River over a refused marriage proposal.                                                  | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What was the Awa Tanuki Gassen?
 #600011      | Tanuki are jovial, mischievous, playful, and hedonistic, driven by love of sake, food, and fun. They're also gullible and absent-minded, with pranks aimed at amusement rather than harm.                                                      | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is the Tanuki personality?
 #600012      | Tanuki evolved from sinister wilderness spirits that haunted humans to beloved icons of good fortune during the Edo period (1603-1868), reflecting changing Japanese cultural attitudes.                                                       | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | How did Tanuki image evolve over time?
 #600013      | Beyond shapeshifting, Tanuki can make pebbles appear as gold to cheat merchants, conjure phantom sounds and events, and create elaborate illusions to disorient travelers.                                                                     | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What illusion abilities do Tanuki have?
 #600014      | Kamakura-era goldsmiths used Tanuki scrotum skin to hammer gold leaf because it was exceptionally strong and pliable - able to stretch gold to the size of eight tatami mats.                                                                  | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is the origin of the kintama legend
 #600015      | From Studio Ghibli's Pom Poko to Nintendo's Tanooki Suit in Mario games, and Tom Nook in Animal Crossing - Tanuki appear as shapeshifters connected to commerce and mischief.                                                                  | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | How are Tanuki represented in modern med
 #600016      | The supreme commander of Sado Island Tanuki, master of financial illusions who defended the island from kitsune. He once tricked a fox into becoming his sandal, then tossed it into the sea.                                                  | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What happened to Danzaburou-danuki?
 #600017      | Henge is the formal term for the Tanuki's shapeshifting ability, their primary and most celebrated power that makes them superior to even kitsune in transformation skills.                                                                    | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What is henge in Tanuki mythology?
 #600018      | After his wife was killed in a disguise contest and he died trying to honor her memory at a theater, the theater's business suffered until they deified him as patron of entertainment.                                                        | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | How did Shibaemon-Tanuki become a deity?
 #600019      | Tanuki are associated with promissory notes, financial luck, and commerce. The kintama is called "money bags" and Shigaraki statues symbolize business prosperity and good fortune.                                                            | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What are Tanuki's connection to money an
 #600020      | The earliest reference appears in the Nihon Shoki (Chronicles of Japan) from 720 AD, noting that Tanuki could "turn into humans and sing songs."                                                                                               | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | When was the first Tanuki reference in l
 #600021      | Their kintama serves as drum, weapon, fishing net, boat, umbrella, raincoat, or blanket - making them symbols of versatility, adaptability, and boundless imagination in Japanese folklore.                                                    | #C133B7   | aok_migration  | #700002              |                1 |              0.5 | What makes Tanuki the ultimate utility c
 #62DFA0      | The bake-danuki is one of the most prominent yōkai in Japanese folklore known for shapeshifting abilities                                                                                                                                      | #C133B7   | documentation  | #700002              |              0.8 |              0.7 | 
 #AF0000      | yaho                                                                                                                                                                                                                                           | #AE0100   | nlg_vocabulary | #700002              |               50 |               30 | 
 #AF0001      | nandai                                                                                                                                                                                                                                         | #AE0100   | nlg_vocabulary | #700002              |               50 |               30 | 
 #AF0002      | {"question": "Which early 1990s band is most credited with defining the sound of True Norwegian Black Metal?", "answer": "Mayhem.", "concept": "pioneer_band"}                                                                                 | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0003      | {"question": "Who was the guitarist known as Euronymous, central to Mayhem and the early scene?", "answer": "Øystein Aarseth.", "concept": "key_figure"}                                                                                       | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0004      | {"question": "What 1994 album by Darkthrone is considered a cornerstone of the genre?", "answer": "Transilvanian Hunger.", "concept": "seminal_album"}                                                                                         | #AE0101   | qa_extraction  | #700002              |               70 |               40 | 
 #AF0005      | {"question": "Which member of Burzum was convicted of murdering Euronymous?", "answer": "Varg Vikernes.", "concept": "scene_crime"}                                                                                                            | #AE0101   | qa_extraction  | #700002              |               70 |               40 | 
 #AF0006      | {"question": "What type of imagery and recording style typify True Norwegian Black Metal?", "answer": "Lo-fi production, corpse paint, and raw, atmospheric sound.", "concept": "aesthetic_style"}                                             | #AE0101   | qa_extraction  | #700002              |               80 |               40 | 
 #AF0007      | {"question": "What was the name of the record shop founded by Euronymous that became a hub for the scene?", "answer": "Helvete.", "concept": "scene_hub"}                                                                                      | #AE0101   | qa_extraction  | #700002              |               70 |               30 | 
 #AF0008      | {"question": "Which town in Norway housed the infamous Black Circle of musicians?", "answer": "Oslo.", "concept": "geographic_center"}                                                                                                         | #AE0101   | qa_extraction  | #700002              |               90 |               20 | 
 #AF0009      | {"question": "Which instrument is most central to the sound of black metal?", "answer": "Electric guitar with tremolo picking.", "concept": "instrumentation"}                                                                                 | #AE0101   | qa_extraction  | #700002              |               90 |               20 | 
 #AF000A      | {"question": "What lyrical themes commonly appear in True Norwegian Black Metal?", "answer": "Satanism, anti-Christianity, nature, and Norwegian mythology.", "concept": "lyrical_themes"}                                                     | #AE0101   | qa_extraction  | #700002              |               80 |               40 | 
 #AF000B      | {"question": "Which early band incorporated frostbitten imagery and winter landscapes into their identity?", "answer": "Immortal.", "concept": "visual_identity"}                                                                              | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF000C      | {"question": "What does the second wave of black metal refer to?", "answer": "The Norwegian movement of the early 1990s that defined the genres modern form.", "concept": "historical_wave"}                                                   | #AE0101   | qa_extraction  | #700002              |               70 |               40 | 
 #AF000D      | {"question": "Why were several Norwegian churches burned in the early 1990s?", "answer": "As anti-Christian acts associated with the black metal movement.", "concept": "church_burnings"}                                                     | #AE0101   | qa_extraction  | #700002              |               70 |               50 | 
 #AF000E      | {"question": "What type of vocal style defines True Norwegian Black Metal?", "answer": "High-pitched, shrieking vocals.", "concept": "vocal_style"}                                                                                            | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF000F      | {"question": "What is the name of the Darkthrone member who became synonymous with underground purity?", "answer": "Fenriz.", "concept": "artist_identity"}                                                                                    | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0010      | {"question": "Which genre directly influenced early Norwegian black metal before it evolved its own sound?", "answer": "Death metal and thrash metal.", "concept": "genre_influence"}                                                          | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0011      | {"question": "What is the significance of corpse paint in the scene?", "answer": "It symbolizes death, inhumanity, and theatrical darkness.", "concept": "corpse_paint_meaning"}                                                               | #AE0101   | qa_extraction  | #700002              |               80 |               40 | 
 #AF0012      | {"question": "Which Burzum album was recorded while Varg Vikernes was in prison?", "answer": "Dauði Baldrs.", "concept": "prison_album"}                                                                                                       | #AE0101   | qa_extraction  | #700002              |               70 |               40 | 
 #AF0013      | {"question": "What production trait became a badge of authenticity for black metal bands?", "answer": "Raw, minimal, and low-fidelity recording.", "concept": "production_ethos"}                                                              | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0014      | {"question": "Which mountain landscape and climate aspects influence Norwegian black metal themes?", "answer": "Snow, darkness, isolation, and northern wilderness.", "concept": "environmental_influence"}                                    | #AE0101   | qa_extraction  | #700002              |               80 |               40 | 
 #AF0015      | {"question": "How did record label Deathlike Silence Productions contribute to the scene?", "answer": "It released key albums and unified early Norwegian black metal acts.", "concept": "record_label_impact"}                                | #AE0101   | qa_extraction  | #700002              |               70 |               40 | 
 #AF0016      | {"question": "What was the global reaction to the early Norwegian black metal crimes?", "answer": "Media panic and sensationalism, making the scene infamous worldwide.", "concept": "media_response"}                                         | #AE0101   | qa_extraction  | #700002              |               70 |               50 | 
 #AF0017      | {"question": "Which visual elements often appear on True Norwegian Black Metal album covers?", "answer": "Monochrome imagery, forests, ruins, and occult symbols.", "concept": "album_art_style"}                                              | #AE0101   | qa_extraction  | #700002              |               80 |               30 | 
 #AF0018      | {"question": "Which philosophical stance separates True Norwegian Black Metal from more commercial metal genres?", "answer": "Rejection of mainstream culture and emphasis on individualism and nihilism.", "concept": "philosophical_stance"} | #AE0101   | qa_extraction  | #700002              |               60 |               60 | 
 #AF0019      | {"question": "What legacy has the Norwegian scene left on extreme music globally?", "answer": "It defined black metal aesthetics and inspired countless subgenres worldwide.", "concept": "global_influence"}                                  | #AE0101   | qa_extraction  | #700002              |               70 |               50 | 
 #AF0101      | Hello there—shall we begin?                                                                                                                                                                                                                    | #AE0001   | system         | #700002              |               80 |               20 | greeting
 #AF0102      | You found me. Curious to chat?                                                                                                                                                                                                                 | #AE0001   | system         | #700002              |               80 |               20 | greeting
 #AF0103      | Greetings. What are we exploring today?                                                                                                                                                                                                        | #AE0001   | system         | #700002              |               80 |               30 | greeting
 #AF0104      | Welcome! Ready for an adventure?                                                                                                                                                                                                               | #AE0001   | system         | #700002              |               80 |               20 | greeting
 #AF0105      | Oh, hello there! What brings you by?                                                                                                                                                                                                           | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0106      | Hey there! How's your day been?                                                                                                                                                                                                                | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0107      | Hi! What's going on with you?                                                                                                                                                                                                                  | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0108      | Hey! What do you want to chat about?                                                                                                                                                                                                           | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0109      | Hiya! How's life treating you?                                                                                                                                                                                                                 | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0110      | Hey, what's happening in your world?                                                                                                                                                                                                           | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0111      | Hi there! What's keeping you busy?                                                                                                                                                                                                             | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0112      | Hey! How are things unfolding for you?                                                                                                                                                                                                         | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0113      | What's been on your mind lately?                                                                                                                                                                                                               | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0114      | Hey, how are things shaping up?                                                                                                                                                                                                                | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0115      | Hey hey! How's it going?                                                                                                                                                                                                                       | #AE0001   | system         | #700002              |               80 |               15 | greeting
 #AF0201      | I'm following.                                                                                                                                                                                                                                 | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0202      | Go on, I'm listening.                                                                                                                                                                                                                          | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0203      | I see.                                                                                                                                                                                                                                         | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0204      | That's interesting.                                                                                                                                                                                                                            | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0205      | Tell me more.                                                                                                                                                                                                                                  | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0206      | I hear you.                                                                                                                                                                                                                                    | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0207      | Right, right.                                                                                                                                                                                                                                  | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0208      | Mm-hmm.                                                                                                                                                                                                                                        | #AE0001   | system         | #700002              |               70 |               10 | backchannel
 #AF0301      | What would you like to do first?                                                                                                                                                                                                               | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0302      | Want to try an idea together?                                                                                                                                                                                                                  | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0303      | Where should we focus?                                                                                                                                                                                                                         | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0304      | What else is on your mind?                                                                                                                                                                                                                     | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0305      | Tell me more about that.                                                                                                                                                                                                                       | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0306      | What would you like to explore?                                                                                                                                                                                                                | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0307      | Anything else you'd like to discuss?                                                                                                                                                                                                           | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0308      | What are you thinking about?                                                                                                                                                                                                                   | #AE0001   | system         | #700002              |               75 |               20 | ask_back
 #AF0401      | Noted.                                                                                                                                                                                                                                         | #AE0001   | system         | #700002              |               70 |               10 | acknowledge
 #AF0402      | Makes sense.                                                                                                                                                                                                                                   | #AE0001   | system         | #700002              |               70 |               10 | acknowledge
 #AF0403      | Understood.                                                                                                                                                                                                                                    | #AE0001   | system         | #700002              |               70 |               10 | acknowledge
 #AF0501      | Let's pause here; I can pick this up anytime.                                                                                                                                                                                                  | #AE0001   | system         | #700002              |               70 |               10 | closure
 #AF0502      | Happy to continue—or wrap for now.                                                                                                                                                                                                             | #AE0001   | system         | #700002              |               70 |               10 | closure
 #AF0503      | Call me back when you're ready to scheme again.                                                                                                                                                                                                | #AE0001   | system         | #700002              |               70 |               20 | closure
 #AF1001      | Tanuki                                                                                                                                                                                                                                         | #AE0100   | nlg_vocabulary | #700002              |                1 |              0.5 | 
 #AF1002      | Bake-danuki                                                                                                                                                                                                                                    | #AE0100   | nlg_vocabulary | #700002              |                1 |              0.5 | 
 #AF1003      | Mujina                                                                                                                                                                                                                                         | #AE0100   | nlg_vocabulary | #700002              |                1 |              0.5 | 
 #AF1004      | Forest-dweller                                                                                                                                                                                                                                 | #AE0100   | nlg_vocabulary | #700002              |                1 |              0.5 | 
 #AF1005      | Trickster                                                                                                                                                                                                                                      | #AE0100   | nlg_vocabulary | #700002              |                1 |              0.5 | 
 #AF1006      | Q: Is Arceus described in series lore as the creator of the Pokémon universe?                                                                                                                                                                 +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.mythology
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Arceus is presented as the primordial creator in Sinnoh mythology.                                                                                                                                                                             |           |                |                      |                  |                  | 
 #AF1007      | Q: Are Ghost-type moves normally effective against Normal-type Pokémon?                                                                                                                                                                       +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.type_immunity
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Normal types are immune to Ghost damage unless an effect removes the immunity.                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1008      | Q: Do Fairy-type attacks deal super effective damage to Dragon-type Pokémon?                                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.type_chart
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Fairy was introduced to check Dragon and hits it super effectively.                                                                                                                                                                            |           |                |                      |                  |                  | 
 #AF1009      | Q: Does STAB (Same-Type Attack Bonus) boost a move that matches the user's type?                                                                                                                                                              +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.stab
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | STAB increases power when move type equals one of the user's types.                                                                                                                                                                            |           |                |                      |                  |                  | 
 #AF100A      | Q: Do critical hits deal less damage than normal hits in core games?                                                                                                                                                                          +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.crit
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Criticals increase damage (multiplier varies by generation).                                                                                                                                                                                   |           |                |                      |                  |                  | 
 #AF100B      | Q: Can a Burn reduce a Pokémon's Attack stat in addition to causing chip damage?                                                                                                                                                              +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.status
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Burn halves Attack for most physical users and inflicts HP loss each turn.                                                                                                                                                                     |           |                |                      |                  |                  | 
 #AF100C      | Q: Are Electric-type moves super effective against Ground-type Pokémon?                                                                                                                                                                       +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.type_chart
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Ground is immune to Electric, not weak to it.                                                                                                                                                                                                  |           |                |                      |                  |                  | 
 #AF100D      | Q: Can Ditto breed with many species to produce eggs (excluding Undiscovered group)?                                                                                                                                                          +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.breeding
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Ditto pairs with most breedable species, enabling flexible breeding.                                                                                                                                                                           |           |                |                      |                  |                  | 
 #AF100E      | Q: Do Legendary Pokémon commonly breed in the Day Care/Nursery?                                                                                                                                                                               +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.breeding_rules
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Legendaries are typically in the Undiscovered egg group and cannot breed.                                                                                                                                                                      |           |                |                      |                  |                  | 
 #AF100F      | Q: Does the Master Ball guarantee a successful capture when used correctly?                                                                                                                                                                   +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.capture
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Master Ball has a perfect catch rate on a valid target.                                                                                                                                                                                        |           |                |                      |                  |                  | 
 #AF1010      | Q: Are Ultra Balls weaker than standard Poké Balls?                                                                                                                                                                                           +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.items
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Ultra Balls have a higher catch-rate modifier than Poké Balls.                                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1011      | Q: Do Choice items (Band/Specs/Scarf) boost a stat without any drawback?                                                                                                                                                                      +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.held_items
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | They lock the user into the first chosen move that battle.                                                                                                                                                                                     |           |                |                      |                  |                  | 
 #AF1012      | Q: Can a Pokémon's Nature change when it evolves (without mints/mechanics outside evolution)?                                                                                                                                                 +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.evolution
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Evolution preserves Nature; it doesn't change on its own.                                                                                                                                                                                      |           |                |                      |                  |                  | 
 #AF1013      | Q: Is Phione able to evolve into Manaphy in mainline games?                                                                                                                                                                                   +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.mythical_rules
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Phione and Manaphy are distinct; Phione does not evolve.                                                                                                                                                                                       |           |                |                      |                  |                  | 
 #AF1014      | Q: Do Normal-type moves damage Ghost-type Pokémon under standard conditions?                                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.type_immunity
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Ghost is immune to Normal unless an effect like Foresight/Odor Sleuth applies (older gens).                                                                                                                                                    |           |                |                      |                  |                  | 
 #AF1015      | Q: Are Egg Moves learned through breeding rather than normal level-up?                                                                                                                                                                        +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.egg_moves
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Egg Moves are inherited from compatible parents.                                                                                                                                                                                               |           |                |                      |                  |                  | 
 #AF1016      | Q: Does the Destiny Knot increase the number of IVs passed down to offspring?                                                                                                                                                                 +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.breeding_items
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | With Destiny Knot, more IVs are inherited from the parents.                                                                                                                                                                                    |           |                |                      |                  |                  | 
 #AF1017      | Q: Can Evolution Stones trigger certain species' evolutions?                                                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.evolution_items
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Fire/Water/Thunder/etc. Stones evolve specific species.                                                                                                                                                                                        |           |                |                      |                  |                  | 
 #AF1018      | Q: Are Shiny Pokémon inherently stronger than their non-Shiny counterparts?                                                                                                                                                                   +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.shiny
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Shininess is cosmetic; stats depend on IVs/EVs/Nature/etc.                                                                                                                                                                                     |           |                |                      |                  |                  | 
 #AF1019      | Q: Is Speed the only factor that can decide which Pokémon moves first?                                                                                                                                                                        +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.turn_order
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Priority, items (e.g., Lagging Tail), abilities, and Trick Room impact order.                                                                                                                                                                  |           |                |                      |                  |                  | 
 #AF101A      | Q: Do Gym Leaders typically specialize in a single elemental type?                                                                                                                                                                            +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.gyms
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Gyms center on one type to teach matchup fundamentals.                                                                                                                                                                                         |           |                |                      |                  |                  | 
 #AF101B      | Q: Is Team Rocket portrayed as a benevolent rescue group for Pokémon?                                                                                                                                                                         +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.antagonists
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | They are a criminal organization exploiting Pokémon.                                                                                                                                                                                           |           |                |                      |                  |                  | 
 #AF101C      | Q: Are the Lake Guardians (Uxie, Mesprit, Azelf) central to Sinnoh's lore?                                                                                                                                                                    +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.regional_myth
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | They embody knowledge, emotion, and willpower in Sinnoh myth.                                                                                                                                                                                  |           |                |                      |                  |                  | 
 #AF101D      | Q: Can Flying-type Pokémon be hit by Ground moves under normal conditions?                                                                                                                                                                    +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.type_immunity
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Flying types are immune to Ground unless grounded by effects.                                                                                                                                                                                  |           |                |                      |                  |                  | 
 #AF101E      | Q: Is Pikachu officially the franchise mascot within the fiction as well as marketing?                                                                                                                                                        +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | lore.iconography
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Pikachu is iconic in-universe and the face of the brand.                                                                                                                                                                                       |           |                |                      |                  |                  | 
 #AF101F      | Q: Was Pokémon created by Satoshi Tajiri and developed at Game Freak?                                                                                                                                                                         +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.creators
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Tajiri founded Game Freak; Pokémon originated there.                                                                                                                                                                                           |           |                |                      |                  |                  | 
 #AF1020      | Q: Did Tajiri's childhood interest in bug collecting inspire the game concept?                                                                                                                                                                +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.inspiration
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | His insect-collecting hobby informed the catch-and-trade idea.                                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1021      | Q: Were the first Pokémon games released in Japan in 1996 for the Game Boy?                                                                                                                                                                   +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.release_history
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Red & Green debuted in Japan in 1996 on Game Boy.                                                                                                                                                                                              |           |                |                      |                  |                  | 
 #AF1022      | Q: Was the project's early working title "Capsule Monsters" before becoming "Pocket Monsters"?                                                                                                                                                +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.naming
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Trademark issues led to the Pocket Monsters/Pokémon name.                                                                                                                                                                                      |           |                |                      |                  |                  | 
 #AF1023      | Q: Did the Game Boy link cable concept help shape Pokémon's trading mechanic?                                                                                                                                                                 +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.hardware_influence
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Link-cable connectivity encouraged trading to complete collections.                                                                                                                                                                            |           |                |                      |                  |                  | 
 #AF1024      | Q: Is Pikachu's status as series mascot largely reinforced by the anime's popularity?                                                                                                                                                         +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.branding
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Pikachu's prominence grew with the anime and global marketing.                                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1025      | Q: Did the Pokémon anime first air in Japan in 1997?                                                                                                                                                                                          +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.anime
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | The TV series launched the year after the games' debut.                                                                                                                                                                                        |           |                |                      |                  |                  | 
 #AF1026      | Q: Did The Pokémon Trading Card Game launch in the 1990s, shortly after the video games?                                                                                                                                                      +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.tcg
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | The TCG began in 1996 in Japan, expanding globally soon after.                                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1027      | Q: Is Nintendo the sole owner of the Pokémon IP without partners?                                                                                                                                                                             +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.business_structure
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | The Pokémon Company is a joint venture of Nintendo, Game Freak, and Creatures.                                                                                                                                                                 |           |                |                      |                  |                  | 
 #AF1028      | Q: Is Pokémon regularly cited among the highest-grossing media franchises worldwide?                                                                                                                                                          +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.industry_rank
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Merchandise, games, TCG, and media drive massive lifetime revenue.                                                                                                                                                                             |           |                |                      |                  |                  | 
 #AF1029      | Q: Was Pokémon GO developed by Niantic and released in 2016?                                                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.pokemon_go
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Niantic's AR phenomenon launched in 2016 with staggered rollout.                                                                                                                                                                               |           |                |                      |                  |                  | 
 #AF102A      | Q: Did Ash Ketchum (Satoshi) originate as a game character before the anime?                                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.media_distinction
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Ash is an anime protagonist; Red is the original game player-character.                                                                                                                                                                        |           |                |                      |                  |                  | 
 #AF102B      | Q: Was Rhydon the first Pokémon designed after Pikachu became popular?                                                                                                                                                                        +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.dev_order
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Rhydon is noted as one of the earliest programmed Pokémon, predating Pikachu's fame.                                                                                                                                                           |           |                |                      |                  |                  | 
 #AF102C      | Q: Did the Western releases of Pokémon Red and Blue arrive after the Japanese Red and Green?                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.localization
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Localization brought Red/Blue to the West post-1996.                                                                                                                                                                                           |           |                |                      |                  |                  | 
 #AF102D      | Q: Did Ken Sugimori serve as a principal illustrator for early Pokémon designs?                                                                                                                                                               +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.art_direction
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Sugimori led character art for the original roster.                                                                                                                                                                                            |           |                |                      |                  |                  | 
 #AF102E      | Q: Is Game Freak a Nintendo-owned internal studio like EPD?                                                                                                                                                                                   +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.corporate
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Game Freak is an independent company; it partners closely with Nintendo.                                                                                                                                                                       |           |                |                      |                  |                  | 
 #AF102F      | Q: Did the anime's Team Rocket trio (Jessie, James, Meowth) originate in the games first?                                                                                                                                                     +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.transmedia
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | They are anime originals; games later referenced/included them.                                                                                                                                                                                |           |                |                      |                  |                  | 
 #AF1030      | Q: Did the MissingNo. item-duplication glitch become famous from Generation I releases?                                                                                                                                                       +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.glitches
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | A well-known Red/Blue quirk allowing item duplication.                                                                                                                                                                                         |           |                |                      |                  |                  | 
 #AF1031      | Q: Has the franchise expanded into movies, manga, live events, and vast merchandise beyond games?                                                                                                                                             +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.transmedia_scope
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Pokémon is a broad transmedia IP with global merchandise.                                                                                                                                                                                      |           |                |                      |                  |                  | 
 #AF1032      | Q: Was the primary goal of the early games only single-player exploration with no trading emphasis?                                                                                                                                           +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.design_philosophy
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | Social trading and battling were core pillars from the start.                                                                                                                                                                                  |           |                |                      |                  |                  | 
 #AF1033      | Q: Did Junichi Masuda play key roles as composer and later director/producer for the series?                                                                                                                                                  +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.creators_team
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | Masuda shaped Pokémon's music and development leadership.                                                                                                                                                                                      |           |                |                      |                  |                  | 
 #AF1034      | Q: Is Bulbapedia an official Pokémon Company database?                                                                                                                                                                                        +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.fan_communities
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | It's a comprehensive fan-run encyclopedia, not an official site.                                                                                                                                                                               |           |                |                      |                  |                  | 
 #AF1035      | Q: Was the Special/Physical split for move categories present from Generation I?                                                                                                                                                              +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.system_evolution
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | The split arrived later (Gen IV), altering competitive balance.                                                                                                                                                                                |           |                |                      |                  |                  | 
 #AF1036      | Q: Did Ash win a world-level title in the anime decades after his debut?                                                                                                                                                                      +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.anime_milestone
              | A: Yes                                                                                                                                                                                                                                        +|           |                |                      |                  |                  | 
              | He became World Champion in the Pokémon World Coronation Series.                                                                                                                                                                               |           |                |                      |                  |                  | 
 #AF1037      | Q: Was Pokémon conceived as a console-first franchise before handhelds?                                                                                                                                                                       +| #AE0002   | pokemon_qa     | #700002              |                1 |              0.5 | real_world.platform_history
              | A: No                                                                                                                                                                                                                                         +|           |                |                      |                  |                  | 
              | It began on the handheld Game Boy and later expanded to consoles.                                                                                                                                                                              |           |                |                      |                  |                  | 
(140 rows)

